import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer"
import AuthProvider from "../context/AuthProvider";



export const metadata: Metadata = {
  title: "Bubble Messenger",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        
      > 
        

            <Navbar/>
            {children}
            <Footer/>
        
        
      </body>
    </html>
  );
}
